Adding linter
UKHomeOffice/lev-web-ui pull request #256
Opened 2024-06-20 15:18 UTC by Hartmannsson-lev

2024-06-25 16:13 UTC, mehar-chauhan commented
Jenkins pipeline: https://lev-ho-hmpo-ew2tlg1nl1-i-team-lev-i-docker-tlg1.np.ebsa.homeoffice.gov.uk/job/apps/job/lev-web-ui/job/LEV-458-eslint/6/console

2024-06-26 14:43 UTC, ashley-bickerstaff-homeoffice requested changes
Need to resolve the issues I've identified before it can be merged.

2024-06-26 14:43 UTC, ashley-bickerstaff-homeoffice commented on eslint.config.mjs
> +      globals: globals.browser
I've run the linter and it was surfacing over 2000 problems... However, most of them are not actual problems. I know the scope of this story isn't to resolve the issues, but I think that the nature of the problems being identified (lots of "require is not defined" type errors) point to the configuration being incorrect.

The following suggestion resolves the vast majority of these. Combined with my other comment in the "ignores" section, it reduces the count to ~700.

```suggestion
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.jest
      }
```

2024-06-26 14:43 UTC, ashley-bickerstaff-homeoffice commented on eslint.config.mjs
> +    ignores: ['dist/']
We need to exclude `/public` too as this contains generated files which we don't have lots of control over:

```suggestion
    ignores: ['dist/', 'public/']
```

2024-06-26 15:26 UTC, ashley-bickerstaff-homeoffice commented on Makefile
> +	npm install && npx eslint . --max-warnings=0 || exit 0
Can we change this to use the npm runner? I think the following will work.

```suggestion
	npm install && npm run lint --max-warnings=0 || exit 0
```

2024-06-27 14:42 UTC, merged