LEV 551 address lint output
UKHomeOffice/lev-web-ui pull request #260
Opened 2024-07-19 14:51 UTC by Hartmannsson-lev

2024-07-19 16:20 UTC, aarongill1 approved these changes

2024-08-13 10:26 UTC, ashley-bickerstaff-homeoffice requested changes

2024-08-13 10:26 UTC, ashley-bickerstaff-homeoffice commented on eslint.config.mjs
> +      'no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }]
I don't think we should have this. I removed it and looked at the results. I'm fairly sure we can just remove unused parameters

2024-08-14 14:55 UTC, ashley-bickerstaff-homeoffice approved these changes

2024-08-22 16:32 UTC, merged